<?php
header('Content-type: text/xml');
echo '<?xml version="1.0" encoding="UTF-8" ?>' . "\n";
echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' . "\n";
echo '<url>' . "\n";
echo '    <loc>' . base_url() . '</loc>' . "\n";
echo '    <lastmod>' . date("Y-m-d H:i:s", strtotime($homepage['update_time'])) . '</lastmod>' . "\n";
echo '    <changefreq>daily</changefreq>' . "\n";
echo '    <priority>1.0</priority>' . "\n";
echo '</url>' . "\n";
echo '<url>' . "\n";
echo '    <loc>' . base_url('/apa-itu-fco') . '</loc>' . "\n";
echo '    <lastmod>' . date("Y-m-d H:i:s", strtotime($apa_itu['updated_time'])) . '</lastmod>' . "\n";
echo '    <changefreq>weekly</changefreq>' . "\n";
echo '    <priority>1.0</priority>' . "\n";
echo '</url>' . "\n";
echo '<url>' . "\n";
echo '    <loc>' . base_url('/bagaimana') . '</loc>' . "\n";
echo '    <lastmod>' . date("Y-m-d H:i:s", strtotime($questions['created_time'])) . '</lastmod>' . "\n";
echo '    <changefreq>weekly</changefreq>' . "\n";
echo '    <priority>0.5</priority>' . "\n";
echo '</url>' . "\n";
echo '<url>' . "\n";
echo '    <loc>' . base_url('/coach') . '</loc>' . "\n";
echo '    <lastmod>2023-10-13 20:58:59</lastmod>' . "\n";
echo '    <changefreq>weekly</changefreq>' . "\n";
echo '    <priority>0.1</priority>' . "\n";
echo '</url>' . "\n";
echo '<url>' . "\n";
echo '    <loc>' . base_url('/testimony') . '</loc>' . "\n";
echo '    <lastmod>' . date("Y-m-d H:i:s", strtotime($testimony['created_time'])) . '</lastmod>' . "\n";
echo '    <changefreq>weekly</changefreq>' . "\n";
echo '    <priority>0.1</priority>' . "\n";
echo '</url>' . "\n";
echo '<url>' . "\n";
echo '    <loc>' . base_url('/article') . '</loc>' . "\n";
echo '    <lastmod>' . date("Y-m-d H:i:s", strtotime($post['created_time'])) . '</lastmod>' . "\n";
echo '    <changefreq>daily</changefreq>' . "\n";
echo '    <priority>1.0</priority>' . "\n";
echo '</url>' . "\n";
foreach ($postList as $row) {
    echo '<url>' . "\n";
    echo '    <loc>' . base_url('/' . $row['slug']) . '</loc>' . "\n";
    echo '    <lastmod>' . date("Y-m-d H:i:s", strtotime(($row['updated_time'] != NULL || $row['updated_time'] != '' ? $row['created_time'] : $row['updated_time']))) . '</lastmod>' . "\n";
    echo '    <changefreq>daily</changefreq>' . "\n";
    echo '    <priority>1.00</priority>' . "\n";
    echo '</url>' . "\n";
}
echo '</urlset>';
